name: Build and Publish

on:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build Wheel
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Build Tools
        run: pip install build

      - name: Build Package
        run: python -m build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/
